default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: password
  socket: /var/run/mysqld/mysqld.sock


development:
  <<: *default
  database: profile-site_development

test:
  <<: *default
  database: profile-site_test

production:
  <<: *default
  database: profile-site_production
  username: root
  password:
